### Getting some stuff
GET http://localhost:3000/songs
Accept: application/json





### Adding a Song



POST http://localhost:3000/songs
Accept: application/json
Content-Type: application/json



{
"title": "I Got You (I Feel Good)",
"artist": "James Brown",
"album": "James Brown's Greatest Hits"
}

### Deleting a Song

DELETE http://localhost:3000/songs/60dcb8b72468582b38b323ca
